<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?= $currentPage ?></title>
    <link rel="stylesheet" href="assets/styles/chat.css" />
</head>

<body>
    <?= var_dump($_SESSION['user']) ?>
    <form action="./controllers/AuthController.php" method="post">
        <input type="hidden" name="type" value="logout"/> 
        <input type="submit" value="Se déconnecter"/>
    </form>
</body>

</html>