<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?= $currentPage ?></title>
    <link rel="stylesheet" href="assets/styles/auth.css" />
</head>

<body>
    <div class="card">
        <h1 class="card__title">Connexion</h1>
        <form action="./controllers/AuthController.php" method="post">
            <input type="hidden" name="type" value="login" />
            <div class="input-group">
                <label for="username">Nom d'utilisateur</label>
                <input type="text" name="username" />
            </div>
            <input type="submit" name="submit" class="btn" value="Se connecter" />
        </form>
    </div>
</body>

</html>